const mockFollowers = [
  {
    login: "TaoRS",
    id: 1037149,
    node_id: "MDQ6VXNlcjEwMzcxNDk=",
    avatar_url: "https://avatars.githubusercontent.com/u/1037149?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/TaoRS",
    html_url: "https://github.com/TaoRS",
    followers_url: "https://api.github.com/users/TaoRS/followers",
    following_url: "https://api.github.com/users/TaoRS/following{/other_user}",
    gists_url: "https://api.github.com/users/TaoRS/gists{/gist_id}",
    starred_url: "https://api.github.com/users/TaoRS/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/TaoRS/subscriptions",
    organizations_url: "https://api.github.com/users/TaoRS/orgs",
    repos_url: "https://api.github.com/users/TaoRS/repos",
    events_url: "https://api.github.com/users/TaoRS/events{/privacy}",
    received_events_url: "https://api.github.com/users/TaoRS/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "monishski",
    id: 50742589,
    node_id: "MDQ6VXNlcjUwNzQyNTg5",
    avatar_url: "https://avatars.githubusercontent.com/u/50742589?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/monishski",
    html_url: "https://github.com/monishski",
    followers_url: "https://api.github.com/users/monishski/followers",
    following_url:
      "https://api.github.com/users/monishski/following{/other_user}",
    gists_url: "https://api.github.com/users/monishski/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/monishski/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/monishski/subscriptions",
    organizations_url: "https://api.github.com/users/monishski/orgs",
    repos_url: "https://api.github.com/users/monishski/repos",
    events_url: "https://api.github.com/users/monishski/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/monishski/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "snowtk",
    id: 75138288,
    node_id: "MDQ6VXNlcjc1MTM4Mjg4",
    avatar_url: "https://avatars.githubusercontent.com/u/75138288?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/snowtk",
    html_url: "https://github.com/snowtk",
    followers_url: "https://api.github.com/users/snowtk/followers",
    following_url: "https://api.github.com/users/snowtk/following{/other_user}",
    gists_url: "https://api.github.com/users/snowtk/gists{/gist_id}",
    starred_url: "https://api.github.com/users/snowtk/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/snowtk/subscriptions",
    organizations_url: "https://api.github.com/users/snowtk/orgs",
    repos_url: "https://api.github.com/users/snowtk/repos",
    events_url: "https://api.github.com/users/snowtk/events{/privacy}",
    received_events_url: "https://api.github.com/users/snowtk/received_events",
    type: "User",
    site_admin: false,
  },
];

export default mockFollowers;
